### ISSUE TITLE
Can you provide an demo written in Vue 3?

### ISSUE THREAD

**Issue by edisonyan** [cucumber/monaco#111]
### 🤔 What's the problem you've observed?

My project is based on Vue3 and Vite. I attempted to modify and use the sample code, but encountered some issues.

### 📚 Any additional context?

Hope to provide a demo based on vue3 and vite,  appreciate it

----

**Comment by kieran-ryan** [comment]
Hello @edisonyan. Would you be able to provide more information that you can provide on the issues you encountered as well as the specific software versions you are using? Preferably, if it is possible to share the repository you are working on, that would be very helpful.
